# Generated by Django 2.1 on 2018-08-19 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
