# Generated by Django 2.1.1 on 2018-09-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_media_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
    ]
